### ISSUE TITLE
Defining a different userModel fails

### ISSUE THREAD

**Issue by justinatack** [UseMuffin/HyperlinkAuth#2]
HI,

I'm trying to use this module with a different user table to the default. I need to use a Members model but the following code is not working.

```
$this->loadComponent('Auth', [
            'authenticate' => [
                'Muffin/HyperlinkAuth.Hyperlink' => [
                    'userModel' => 'Members'
                ]
            ]
        ]);
```

Any ideas?

**Comment by ADmad** [comment]
The `userModel` config is unrelated to redirection. You need to specify `loginAction` in AuthComponent config.

**Comment by justinatack** [comment]
The problem is to do with using a different table/model other than Users. I want to use Members and i cannot change it.

**Comment by ADmad** [comment]
Earlier you said "I keep getting redirected to users/login but it should go to members/login"  and now you say "I have no issues with the redirect.".  So which one is it?

The `userModel` config is used as expected when fetching table object [here](https://github.com/UseMuffin/HyperlinkAuth/blob/master/src/Auth/HyperlinkAuthenticate.php#L77).
